# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yayun Liu's Blog
brief-intro: Engineer, Blogger, Learner
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yayunl.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
github_username:  yayunl
email: yayunliu90@gmail.com
linkedIn_username: yayunliu1990

description_footer: Welcome to Yayun Liu's personal website！

# comments
disqus_shortname: https-yayunl-github-io

google_analytics_id: G-G6XFMTHQE9 # google measurement id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 10

## mermaid
#mermaid:
#  src: "assets/js/mermaid.js"

plugins:
  - jekyll-paginate

